//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repaso.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Contactos
    {
        public int Id { get; set; }

    
        [Required(ErrorMessage = "{0} es requerido")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "{0} es requerido")]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "{0} es requerido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "{0} es requerido")]
        public string Telefono { get; set; }

        [Required(ErrorMessage = "{0} es requerido")]
        public string Mensaje { get; set; }
    }
}
